### ISSUE TITLE
Add a readme

### ISSUE THREAD

**Issue by ghost** [nodesagency/blog#100]
Please provide steps on how to contribute to the blog. 

* how to run site locally
* how to deploy
* how to contribute content
* how to add images (setup nstack keys)

**Comment by emrahsifoglu** [comment]
@roxanajula, do you think the [readme](https://github.com/nodesagency/nodesagency.github.io) is good enough so I can close this issue?

**Comment by roxanajula** [comment]
The new readme of the blog has all information now.
