### ISSUE TITLE
Support multiple author ids per article

### ISSUE THREAD

**Issue by nickskull** [nodesagency/blog#15]
Preferably comma separated list:

```
authorId: doha,maco,dhni
```

**Comment by dennishn** [comment]
I will be able to get this to work, the frontmatter will be formatted like this:
```
authorId:
- doha
- maco
- dhni
```

Todo:
- [ ] Fork hexo-multiauthor and update code to support arrays of authors
- [ ] Release new plugin under nodes-frontend
- [ ] Add author partials (with / without twitter)
- [ ] Add author card list partial

Will take a few hours, but i'll make it happen!

**Comment by nickskull** [comment]
Absolutely awesome 🎉 🏌️ 👍

**Comment by dennishn** [comment]
The property in the frontmatter has been changed to `authorIds` (plural).
https://www.npmjs.com/package/hexo-multiauthors Package released!

**Comment by mariusc** [comment]
The NSSpain article doesn't correctly display the authors - https://engineering.nodesagency.com/articles/iOS/Insights-from-NSSpain/

The frontmatter looks like this:

    authorIds: 
    - doha
    - maco
    - jmje

Raw content here: https://raw.githubusercontent.com/nodesagency/blog/master/source/_posts/2016-10-01-Insights-from-NSSpain.md

**Comment by dennishn** [comment]
Diddly Done-a-roonie
