### ISSUE TITLE
Small improvements for the DroidCon article

### ISSUE THREAD

**Issue by mariusc** [nodesagency/blog#57]
https://tech-blog.staging-like.st/articles/Android/DroidCon-London-2016/

![image](https://cloud.githubusercontent.com/assets/844175/20351839/20285efa-ac15-11e6-80f2-3bfc9149f8b8.png)

- [x] A small introduction would be nice. Something along the lines of "DroidCon is a conference for Android developers; 3 persons from our team attended it. Here's what we learnt from it". But with more words than what I wrote :D. 
- [x] The "Johnny, Mobile Lead" text looks a bit out of place. Was the idea to have everyone who attended write something and the others didn't do it? Otherwise, the name of the author already appears at the top of the page, so I think this is redundant.
- [x] Wrong link syntax for https://developer.android.com/training/safetynet/index.html
- [x] It would be nice to have paragraphs longer than 1 sentence. The text seems very fragmented, both when you look at it and also when you read it. Can we try to connect those ideas into more complex paragraphs?
- [x] In the Android Application Security section, it would be awesome if we used a list for Android 7, Android 6 and Android 5, instead of a separate paragraph for each.

**Comment by nickskull** [comment]
I agree, and especially with the point about short paragraphs and so many line breaks. It makes it hard to read and even then it seems like reading bullet points 👼

**Comment by mariusc** [comment]
Fixed in https://github.com/nodesagency/blog/pull/60. Closing this.
