### ISSUE TITLE
Index page is showing old content unless I force refresh

### ISSUE THREAD

**Issue by Casperhr** [nodesagency/blog#6]
There most be some heavy caching

**Comment by dennishn** [comment]
It is indeed insanely heavily cached! I will look into a way to bust the caches, but i want to keep the "feature" as it should make our content available to people on bad connections or even if they are offline.

**Comment by dennishn** [comment]
We now show a toast message when content has been updated, asking users to refresh. This is the same behavior as other offline capable sites.
