### ISSUE TITLE
"Back to Nodes" has rel=nofollow tag

### ISSUE THREAD

**Issue by pedersenmark** [nodesagency/blog#62]
Just a minor thing, but is there any reason for the "Back to Nodes" link is tagged as nofollow? 

From my point of view, it would not be harmful in any way, and only improve nodesagency.com to make it follow instead of nofollow.

**Comment by Casperhr** [comment]
@dennishn can you fix that ?

**Comment by dennishn** [comment]
@Casperhr Yep

**Comment by dennishn** [comment]
done

**Comment by pedersenmark** [comment]
Awesome, thanks!
