### ISSUE TITLE
Investigate the idea of increasing the article body font or removing the serifs

### ISSUE THREAD

**Issue by mariusc** [nodesagency/blog#72]
After a short discussion on our slack with @nickskull and @johsoe, we should probably look into updating the article fonts a bit. We all agreed that it's not very easy to read as it is now. However, we couldn't easily agree on how exactly we should change it.

Here's a version with body text without serifs (not sure what font size was used here) and headers with serifs.
![image](https://cloud.githubusercontent.com/assets/844175/23456901/a9e815a6-fe75-11e6-914f-fa673c5fd8f2.png)

And here's a version with body text with serifs but with a font size of 21 (and bold headers with serifs)
![image](https://cloud.githubusercontent.com/assets/844175/23456938/d59b4e3e-fe75-11e6-885c-8188e8feddd5.png)

Not sure exactly which approach should be chosen, but it would be nice to do something to make the articles more easily readable.

**Comment by roxanajula** [comment]
Not relevant anymore due to blog redesign
