### ISSUE TITLE
Wrong date format

### ISSUE THREAD

**Issue by mariusc** [nodesagency/blog#98]
Hey @jakobmygind :)

I noticed that the latest article added uses a wrong date format. It should be yyyy-MM-dd, not yyyy-dd-MM. This led to it appearing on the website dated next year 😄.

![image](https://user-images.githubusercontent.com/844175/32599657-d5cf5f84-c545-11e7-9746-8744e4372a22.png)

A similar issue seems to be with the next article, the one @selynodes is writing 

https://github.com/nodesagency/blog/blob/feature/chaleswebproxy/source/_posts/2017-08-11-How-we-debug-with-Charles.md

**Comment by selynodes** [comment]
@mariusc thanks for letting me know :) I shall fix it . Hope you are doing good!

**Comment by jakobmygind** [comment]
Hi Marius! 

Thanks, I’ll fix it if Sely didn’t already :)

Hope you are well!
-- 

Jakob Mygind
Senior iOS Developer
Nodes
Copenhagen // Artillerivej 86, 2300 Copenhagen, Denmark 
Aarhus // Frederiksgade 45, 2. sal, 8000 Aarhus, Denmark 
London // 174 North Gower Street, London NW1 2NB, United Kingdom

Mobile: +45 2680 5243
Web: http://www.nodes.dk <http://www.nodes.dk/>

**Comment by roxanajula** [comment]
Fixed this in #107
