### ISSUE TITLE
Images on "Searchable Items" article look weird

### ISSUE THREAD

**Issue by mariusc** [nodesagency/blog#99]
The images are rendered one per line

![image](https://user-images.githubusercontent.com/844175/32600076-10b02bfa-c547-11e7-97a8-e70e7a1a92a4.png)

It looks like there's a `<br>` in between them in the source of the rendered html:

![image](https://user-images.githubusercontent.com/844175/32600160-60b63e6e-c547-11e7-90b2-d316f8b31bfe.png)

It could be because in the .md source there's a newline between them. 
![image](https://user-images.githubusercontent.com/844175/32600179-6fba768c-c547-11e7-823f-ad967fdc6a4a.png)

Maybe having them on one row in the markdown file fixes the weird alignment on the website :)

**Comment by emrahsifoglu** [comment]
This issue seems has been fixed thus I am closing this issue.
